<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/yii2basic-template';

return array(
    'yii\\swiftmailer\\' => array($vendorDir . '/yiisoft/yii2-swiftmailer'),
    'yii\\jui\\' => array($vendorDir . '/yiisoft/yii2-jui'),
    'yii\\gii\\' => array($vendorDir . '/yiisoft/yii2-gii'),
    'yii\\faker\\' => array($vendorDir . '/yiisoft/yii2-faker'),
    'yii\\debug\\' => array($vendorDir . '/yiisoft/yii2-debug'),
    'yii\\composer\\' => array($vendorDir . '/yiisoft/yii2-composer'),
    'yii\\codeception\\' => array($vendorDir . '/yiisoft/yii2-codeception'),
    'yii\\bootstrap\\' => array($vendorDir . '/yiisoft/yii2-bootstrap'),
    'yii\\authclient\\' => array($vendorDir . '/yiisoft/yii2-authclient'),
    'yii\\' => array($vendorDir . '/yiisoft/yii2'),
    'skeeks\\yii2\\mobiledetect\\' => array($vendorDir . '/skeeks/yii2-mobile-detect'),
    'skeeks\\yii2\\assetsAuto\\' => array($vendorDir . '/skeeks/yii2-assets-auto-compress'),
    'sfedosimov\\daysago\\' => array($vendorDir . '/sfedosimov/yii2-daysago'),
    'moonland\\phpexcel\\' => array($vendorDir . '/moonlandsoft/yii2-phpexcel'),
    'miloschuman\\highcharts\\' => array($vendorDir . '/miloschuman/yii2-highcharts-widget/src'),
    'kartik\\select2\\' => array($vendorDir . '/kartik-v/yii2-widget-select2'),
    'kartik\\popover\\' => array($vendorDir . '/kartik-v/yii2-popover-x'),
    'kartik\\plugins\\popover\\' => array($vendorDir . '/kartik-v/bootstrap-popover-x'),
    'kartik\\mpdf\\' => array($vendorDir . '/kartik-v/yii2-mpdf'),
    'kartik\\grid\\' => array($vendorDir . '/kartik-v/yii2-grid'),
    'kartik\\editable\\' => array($vendorDir . '/kartik-v/yii2-editable'),
    'kartik\\base\\' => array($vendorDir . '/kartik-v/yii2-krajee-base'),
    'julianb90\\seomanager\\' => array($vendorDir . '/julian-b90/yii2-seomanager'),
    'imanilchaudhari\\CurrencyConverter\\' => array($vendorDir . '/imanilchaudhari/yii2-currency-converter'),
    'ibrarturi\\latlngfinder\\' => array($vendorDir . '/ibrarturi/yii2-latlng-finder'),
    'ho96\\extplorer\\' => array($vendorDir . '/ho96/yii2-extplorer'),
    'giovdk21\\yii2SyntaxHighlighter\\' => array($vendorDir . '/giovdk21/yii2-syntaxhighlighter'),
    'fedemotta\\cronjob\\' => array($vendorDir . '/fedemotta/yii2-cronjob'),
    'etsoft\\widgets\\' => array($vendorDir . '/et-soft/yii2-widget-select-year'),
    'dosamigos\\highcharts\\' => array($vendorDir . '/2amigos/yii2-highcharts-widget/src'),
    'dektrium\\user\\' => array($vendorDir . '/dektrium/yii2-user'),
    'dektrium\\rbac\\' => array($vendorDir . '/dektrium/yii2-rbac'),
    'cebe\\markdown\\' => array($vendorDir . '/cebe/markdown'),
    'XMLSoccer\\' => array($vendorDir . '/drsdre/yii2-xmlsoccer'),
    'Faker\\' => array($vendorDir . '/fzaninotto/faker/src/Faker'),
);
